// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenartRing.Data;

#nullable disable

namespace RenartRing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250705124958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RenartRing.Models.Ring", b =>
                {
                    b.Property<int>("RingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PopularityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("RingId");

                    b.ToTable("Rings");
                });

            modelBuilder.Entity("RenartRing.Models.Ring", b =>
                {
                    b.OwnsOne("RenartRing.Models.RingColors", "Images", b1 =>
                        {
                            b1.Property<int>("RingId")
                                .HasColumnType("integer");

                            b1.Property<string>("Rose")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("White")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Yellow")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RingId");

                            b1.ToTable("Rings");

                            b1.WithOwner()
                                .HasForeignKey("RingId");
                        });

                    b.Navigation("Images")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
